# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    # checkout
    - name: Check out repository code
      uses: actions/checkout@v2
        
    # install on frontend
    - run: npm i
      working-directory: ./frontend
    
    # Substitute secret for the frontend part
    - name: Substitute frontend env file
      uses: bluwy/substitute-string-action@v1
      id: sub-frontend
      with:
        _input-file: './frontend/.env'
        _format-key: '%%key%%'
        stripe_key: ${{ secrets.REACT_APP_STRIPE_KEY }}
        
    # install on backend
    - run: npm i
      working-directory: ./backend
    
    # Substitute secret for the frontend part
    - name: Substitute backend env file
      uses: bluwy/substitute-string-action@v1
      id: sub-backend
      with:
        _input-file: './backend/.env'
        _format-key: '%%key%%'
        stripe_secret: ${{ secrets.STRIPE_SECRET }}
        database: ${{ secrets.DATABASE }}
        port: ${{ secrets.PORT }}
        jwt: ${{ secrets.JWT_SECRET }}
        stripe_redirect: ${{ secrets.STRIPE_REDIRECT_URL }}
        stripe_setting_redirect: ${{ secrets.STRIPE_SETTING_REDIRECT_URL }}
        
    
    # send files of frontend
    - name: Deploy frontend files via SSH
      uses: appleboy/scp-action@master
      with:
        host: 164.90.175.228
        username: root
        password: dy#3d#v2Y7JQAT
        source: "frontend/*"
        target: "frontend"
        
    # send files of backend
    - name: Deploy backend files via SSH
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: 164.90.175.228
        password: dy#3d#v2Y7JQAT
        localDir: backend
        remoteDir: backend
          
      # connect to the droplet and npm start for backend and frontend
    - name: Execute SSH commmands on remote server
      uses: tarunjangra/ssh-remote-cmd@v1
      with:
          # Trouver un moyen pour récupérer les fichiers digital-oceans-deploy.env et docker-compose-deploy.yml
          command: |
            cd frontend/ && (npm run start&)
            cd ../backend/ && (npm run start&)
          host: 164.90.175.228
          user: root
          pass: dy#3d#v2Y7JQAT
